/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import DAO.ProdutoDAO;
import Entidades.Produto;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Igor
 */
public class NovoProduto extends javax.swing.JFrame {

    /**
     * Creates new form NovoProduto
     */
    String user = "";
    String senha = "";
    public NovoProduto(String user, String senha) {
        initComponents();
        this.user = user;
        this.senha = senha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        tf_qntd = new javax.swing.JTextField();
        cb_modo = new javax.swing.JComboBox();
        cb_categoria = new javax.swing.JComboBox();
        jb_cadastrar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Nome:");

        jLabel2.setText("Quantidade em estoque:");

        jLabel3.setText("Modo:");

        jLabel4.setText("Categoria:");

        tf_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_nomeKeyPressed(evt);
            }
        });

        tf_qntd.setText("0");
        tf_qntd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_qntdKeyPressed(evt);
            }
        });

        cb_modo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KG", "UND", "L", "mL", "g" }));
        cb_modo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cb_modoKeyPressed(evt);
            }
        });

        cb_categoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CONGELADOS", "CARNES", "AVES", "PEIXES E FRUTOS DO MAR", "HORTIFRUT", "SUSHI", "MERCEARIA", "PADARIA E CONFEITARIA", "FRIOS E LATICÍNIOS", "LIMPEZA E DESCARTÁVEIS" }));
        cb_categoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cb_categoriaKeyPressed(evt);
            }
        });

        jb_cadastrar.setText("Cadastrar");
        jb_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cadastrarActionPerformed(evt);
            }
        });
        jb_cadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_cadastrarKeyPressed(evt);
            }
        });

        jb_cancelar.setText("Cancelar");
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });
        jb_cancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_cancelarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_modo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_qntd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jb_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_qntd, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_modo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(440, 398));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cadastrarActionPerformed
        // TODO add your handling code here:]
        Produto p = new Produto();
        
        p.setNome(tf_nome.getText());
        p.setModo(String.valueOf(cb_modo.getSelectedItem()));
        p.setCategoria(String.valueOf(cb_categoria.getSelectedItem()));
        p.setQuant(Double.parseDouble(tf_qntd.getText()));
        
        ProdutoDAO dao;
        try {
            dao = new ProdutoDAO();
            dao.inserirProduto(p);
        } catch (SQLException ex) {
            Logger.getLogger(NovoProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        tf_nome.setText("");
        tf_qntd.setText("");
        tf_nome.grabFocus();
        
        
    }//GEN-LAST:event_jb_cadastrarActionPerformed

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        // TODO add your handling code here
        new TelaProdutos(user, senha).show();
        dispose();
    }//GEN-LAST:event_jb_cancelarActionPerformed

    private void tf_nomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nomeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            jb_cancelarActionPerformed(null);
            
    }//GEN-LAST:event_tf_nomeKeyPressed

    private void tf_qntdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_qntdKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_tf_qntdKeyPressed

    private void cb_modoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_modoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_cb_modoKeyPressed

    private void cb_categoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_categoriaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_cb_categoriaKeyPressed

    private void jb_cadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_cadastrarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_jb_cadastrarKeyPressed

    private void jb_cancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_cancelarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            jb_cadastrarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_jb_cancelarKeyPressed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb_categoria;
    private javax.swing.JComboBox cb_modo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jb_cadastrar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_qntd;
    // End of variables declaration//GEN-END:variables
}
