/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import DAO.ProdutoDAO;
import DAO.RetiroDAO;
import Entidades.Produto;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Igor
 */
public class RetirarEstoque extends javax.swing.JFrame {

    /**
     * Creates new form ReporEstoque
     */
    String user = "";
    String senha = "";
    private final Produto p;
    private final TelaProdutos tp;
    int cont = 0;
    
    public RetirarEstoque(java.awt.Frame parent, boolean modal, Produto p, TelaProdutos tp, String user, String senha) {
        initComponents();
        this.p = p;
        this.tp = tp;
        carregarCampos();
        this.user = user;
        this.senha = senha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jl_quantAt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_quantR = new javax.swing.JTextField();
        jb_repor = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Quantidade atual:");

        jLabel3.setText("Quantidade retirada:");

        tf_quantR.setText("0");
        tf_quantR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_quantRKeyPressed(evt);
            }
        });

        jb_repor.setText("Retirar");
        jb_repor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_reporActionPerformed(evt);
            }
        });
        jb_repor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_reporKeyPressed(evt);
            }
        });

        jb_cancelar.setText("Cancelar");
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });
        jb_cancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_cancelarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jl_quantAt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_quantR, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jb_repor, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jb_cancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_quantAt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_quantR, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_repor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(416, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_reporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_reporActionPerformed
        // TODO add your handling code here:
        p.setQuant((p.getQuant() - Double.parseDouble(tf_quantR.getText())));
        if(p.getQuant()<0){
            JOptionPane.showMessageDialog(null, "Quantidade no estoque é insuficiente!!");
            tf_quantR.setText("");
            tf_quantR.grabFocus();
        }else{
        try {
            double ret = Double.parseDouble(tf_quantR.getText());
            ProdutoDAO dao = new ProdutoDAO();
            RetiroDAO rdao = new RetiroDAO();
            dao.reporEstoque(p);
            rdao.addRetiro(p, ret);
            new TelaProdutos(user, senha).show();
            dispose();
            
        } catch (SQLException ex) {
            Logger.getLogger(ReporEstoque.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
    }//GEN-LAST:event_jb_reporActionPerformed

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        // TODO add your handling code here:
        new TelaProdutos(user, senha).show();
        dispose();
    }//GEN-LAST:event_jb_cancelarActionPerformed

    private void tf_quantRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_quantRKeyPressed
        // TODO add your handling code here:
        if(cont!=0){
            
        }else{
        tf_quantR.setText("");
        cont++;
        }
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            jb_reporActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_tf_quantRKeyPressed

    private void jb_reporKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_reporKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            jb_reporActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_jb_reporKeyPressed

    private void jb_cancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_cancelarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            jb_reporActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            jb_cancelarActionPerformed(null);
    }//GEN-LAST:event_jb_cancelarKeyPressed

    /**
     * @param args the command line arguments
     */
   
    public void carregarCampos(){
        
        jl_quantAt.setText(String.valueOf(p.getQuant())+p.getModo());
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_repor;
    private javax.swing.JLabel jl_quantAt;
    private javax.swing.JTextField tf_quantR;
    // End of variables declaration//GEN-END:variables
}
