/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import DAO.ProdutoDAO;
import Entidades.Produto;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Igor
 */
public class TelaProdutos extends javax.swing.JFrame {

    /**
     * Creates new form TelaProdutos
     */
    String user = "";
    String senha = "";
    String pesq = "";
    List<Produto> minhaList = new ArrayList<Produto>();
    String filtro = "";
    public TelaProdutos(String user, String senha) {
        initComponents();
        try {
            preencherTabela();
        } catch (SQLException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.user = user;
        this.senha = senha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoria = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_prod = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jb_novo = new javax.swing.JButton();
        jb_editar = new javax.swing.JButton();
        jb_repor = new javax.swing.JButton();
        jb_deletar = new javax.swing.JButton();
        jb_retirar = new javax.swing.JButton();
        jb_relatorio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tf_pesq = new javax.swing.JTextField();
        rb_congelados = new javax.swing.JRadioButton();
        rb_carnes = new javax.swing.JRadioButton();
        rb_aves = new javax.swing.JRadioButton();
        rb_peixes = new javax.swing.JRadioButton();
        rb_frios = new javax.swing.JRadioButton();
        rb_hort = new javax.swing.JRadioButton();
        rb_limpeza = new javax.swing.JRadioButton();
        rb_mercearia = new javax.swing.JRadioButton();
        rb_padaria = new javax.swing.JRadioButton();
        rb_sushi = new javax.swing.JRadioButton();
        rb_todos = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_novoUser = new javax.swing.JMenuItem();
        mi_editUser = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mi_sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tb_prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_prod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_prodKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb_prod);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );

        jb_novo.setText("Novo ");
        jb_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_novoActionPerformed(evt);
            }
        });
        jb_novo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_novoKeyPressed(evt);
            }
        });

        jb_editar.setText("Editar");
        jb_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_editarActionPerformed(evt);
            }
        });
        jb_editar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_editarKeyPressed(evt);
            }
        });

        jb_repor.setText("Repor estoque");
        jb_repor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_reporActionPerformed(evt);
            }
        });
        jb_repor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_reporKeyPressed(evt);
            }
        });

        jb_deletar.setText("Deletar produto");
        jb_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_deletarActionPerformed(evt);
            }
        });
        jb_deletar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_deletarKeyPressed(evt);
            }
        });

        jb_retirar.setText("Retirar estoque");
        jb_retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_retirarActionPerformed(evt);
            }
        });
        jb_retirar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_retirarKeyPressed(evt);
            }
        });

        jb_relatorio.setText("Relatório de entrada e saída");
        jb_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_relatorioActionPerformed(evt);
            }
        });
        jb_relatorio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_relatorioKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jb_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_repor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_deletar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_retirar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_relatorio)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_repor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_retirar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Pesquisa");

        tf_pesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_pesqKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_pesqKeyReleased(evt);
            }
        });

        categoria.add(rb_congelados);
        rb_congelados.setText("CONGELADOS");
        rb_congelados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_congeladosActionPerformed(evt);
            }
        });
        rb_congelados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_congeladosKeyPressed(evt);
            }
        });

        categoria.add(rb_carnes);
        rb_carnes.setText("CARNES");
        rb_carnes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_carnesActionPerformed(evt);
            }
        });
        rb_carnes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_carnesKeyPressed(evt);
            }
        });

        categoria.add(rb_aves);
        rb_aves.setText("AVES");
        rb_aves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_avesActionPerformed(evt);
            }
        });
        rb_aves.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_avesKeyPressed(evt);
            }
        });

        categoria.add(rb_peixes);
        rb_peixes.setText("PEIXES E FRUTOS DO MAR");
        rb_peixes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_peixesActionPerformed(evt);
            }
        });
        rb_peixes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_peixesKeyPressed(evt);
            }
        });

        categoria.add(rb_frios);
        rb_frios.setText("FRIOS E LATICÍNIOS");
        rb_frios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_friosActionPerformed(evt);
            }
        });
        rb_frios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_friosKeyPressed(evt);
            }
        });

        categoria.add(rb_hort);
        rb_hort.setText("HORTIFRUT");
        rb_hort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_hortActionPerformed(evt);
            }
        });
        rb_hort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_hortKeyPressed(evt);
            }
        });

        categoria.add(rb_limpeza);
        rb_limpeza.setText("LIMPEZA E DESCARTÁVEIS");
        rb_limpeza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_limpezaActionPerformed(evt);
            }
        });
        rb_limpeza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_limpezaKeyPressed(evt);
            }
        });

        categoria.add(rb_mercearia);
        rb_mercearia.setText("MERCEARIA");
        rb_mercearia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_merceariaActionPerformed(evt);
            }
        });
        rb_mercearia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_merceariaKeyPressed(evt);
            }
        });

        categoria.add(rb_padaria);
        rb_padaria.setText("PADARIA E CONFEITARIA");
        rb_padaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_padariaActionPerformed(evt);
            }
        });
        rb_padaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_padariaKeyPressed(evt);
            }
        });

        categoria.add(rb_sushi);
        rb_sushi.setText("SUSHI");
        rb_sushi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_sushiActionPerformed(evt);
            }
        });
        rb_sushi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_sushiKeyPressed(evt);
            }
        });

        categoria.add(rb_todos);
        rb_todos.setSelected(true);
        rb_todos.setText("TODOS");
        rb_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_todosActionPerformed(evt);
            }
        });
        rb_todos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rb_todosKeyPressed(evt);
            }
        });

        jMenu1.setText("Usuário");

        mi_novoUser.setText("Novo Usuário");
        mi_novoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_novoUserActionPerformed(evt);
            }
        });
        jMenu1.add(mi_novoUser);

        mi_editUser.setText("Editar Usuário Atual");
        mi_editUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_editUserActionPerformed(evt);
            }
        });
        jMenu1.add(mi_editUser);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opções");

        mi_sair.setText("Sair");
        mi_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_sairActionPerformed(evt);
            }
        });
        jMenu2.add(mi_sair);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(233, 233, 233)
                                        .addComponent(rb_todos))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rb_congelados)
                                            .addComponent(rb_mercearia))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rb_padaria)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rb_frios))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rb_carnes)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rb_aves)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rb_peixes)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rb_hort)
                                                .addGap(11, 11, 11)
                                                .addComponent(rb_sushi))
                                            .addComponent(rb_limpeza)))))
                            .addComponent(tf_pesq, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_pesq, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rb_todos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_congelados)
                    .addComponent(rb_carnes)
                    .addComponent(rb_aves)
                    .addComponent(rb_peixes)
                    .addComponent(rb_hort)
                    .addComponent(rb_sushi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_mercearia)
                    .addComponent(rb_padaria)
                    .addComponent(rb_frios)
                    .addComponent(rb_limpeza))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(904, 562));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novoActionPerformed
        // TODO add your handling code here:
        new NovoProduto(user, senha).show();
        dispose();
    }//GEN-LAST:event_jb_novoActionPerformed

    private void rb_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_todosActionPerformed
        // TODO add your handling code here:
        filtro = "";
        try {
            preencherTabela();
        } catch (SQLException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rb_todosActionPerformed

    private void rb_congeladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_congeladosActionPerformed
        // TODO add your handling code here:
        filtro= "CONGELADOS";
        try {
            preencherTabela();
        } catch (SQLException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rb_congeladosActionPerformed

    private void rb_carnesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_carnesActionPerformed
        // TODO add your handling code here:
        filtro= "CARNES";
        try {
            preencherTabela();
        } catch (SQLException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rb_carnesActionPerformed

    private void rb_avesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_avesActionPerformed
        // TODO add your handling code here:
        filtro= "AVES";
        try {
            preencherTabela();
        } catch (SQLException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rb_avesActionPerformed

    private void rb_peixesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_peixesActionPerformed
        // TODO add your handling code here:
        filtro= "PEIXES E FRUTOS DO MAR";
        try {
            preencherTabela();
        } catch (SQLException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rb_peixesActionPerformed

    private void rb_hortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_hortActionPerformed
        // TODO add your handling code here:
        filtro= "HORTIFRUT";
        try {
            preencherTabela();
        } catch (SQLException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rb_hortActionPerformed

    private void rb_sushiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_sushiActionPerformed
        // TODO add your handling code here:
        filtro= "SUSHI";
        try {
            preencherTabela();
        } catch (SQLException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rb_sushiActionPerformed

    private void rb_merceariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_merceariaActionPerformed
        // TODO add your handling code here:
        filtro= "MERCEARIA";
        try {
            preencherTabela();
        } catch (SQLException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rb_merceariaActionPerformed

    private void rb_padariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_padariaActionPerformed
        // TODO add your handling code here:
        filtro= "PADARIA E CONFEITARIA";
        try {
            preencherTabela();
        } catch (SQLException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rb_padariaActionPerformed

    private void rb_friosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_friosActionPerformed
        // TODO add your handling code here:
        filtro= "FRIOS E LATICÍNIOS";
        try {
            preencherTabela();
        } catch (SQLException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rb_friosActionPerformed

    private void rb_limpezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_limpezaActionPerformed
        // TODO add your handling code here:
        filtro= "LIMPEZA E DESCARTÁVEIS";
        try {
            preencherTabela();
        } catch (SQLException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rb_limpezaActionPerformed

    private void jb_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_deletarActionPerformed
        // TODO add your handling code here:
        Produto p = new Produto();
        ProdutoDAO dao = null;
        try {
            dao = new ProdutoDAO();
        } catch (SQLException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (JOptionPane.showConfirmDialog(null, "Deseja mesmo excluir?", "Confirmação de exclusão", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        
            try {
                p =(Produto) minhaList.get(tb_prod.getSelectedRow());
                dao.excluirProduto(p);
                tf_pesq.setText("");
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro");
            }
        }
                    
        try { 
            preencherTabela();
        } catch (SQLException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_deletarActionPerformed

    private void jb_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_editarActionPerformed
        // TODO add your handling code here:
        Produto p = new Produto();
        if (tb_prod.getSelectedRow() != -1) {
            
          p = (Produto) minhaList.get(tb_prod.getSelectedRow()); 
          
          EditarProduto dialog = new EditarProduto(this, true, p, this, user, senha);            
          dialog.setVisible(true);
          dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um registro", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jb_editarActionPerformed

    private void jb_reporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_reporActionPerformed
        // TODO add your handling code here:
        Produto p = new Produto();
        if (tb_prod.getSelectedRow() != -1) {
            
          p = (Produto) minhaList.get(tb_prod.getSelectedRow()); 
          
          ReporEstoque dialog = new ReporEstoque(this, true, p, this, user, senha);            
          dialog.setVisible(true);
          dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um registro", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jb_reporActionPerformed

    private void jb_retirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_retirarActionPerformed
        // TODO add your handling code here:
        Produto p = new Produto();
        if (tb_prod.getSelectedRow() != -1) {
            
          p = (Produto) minhaList.get(tb_prod.getSelectedRow()); 
          
          RetirarEstoque dialog = new RetirarEstoque(this, true, p, this, user, senha);            
          dialog.setVisible(true);
          dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um registro", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jb_retirarActionPerformed

    private void tf_pesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pesqKeyReleased
        // TODO add your handling code here:
        pesq = tf_pesq.getText();
        String ant = "";
        try {
            ProdutoDAO dao = new ProdutoDAO();
            if(pesq.equals("")){
                preencherTabela();
            }else{
              minhaList =  dao.ListPesq(pesq, filtro);
              preecherTabelaPesq(minhaList);
              ant = pesq;
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Funcionário não encontrado!!", "Erro", JOptionPane.ERROR_MESSAGE);
            tf_pesq.setText(ant);
        } catch (ParseException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tf_pesqKeyReleased

    private void jb_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_relatorioActionPerformed
        // TODO add your handling code here:
        new Relatorio().show();
    }//GEN-LAST:event_jb_relatorioActionPerformed

    private void jb_novoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_novoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_reporActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_retirarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_relatorioActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            fecharSys();
    }//GEN-LAST:event_jb_novoKeyPressed

    private void jb_editarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_editarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_reporActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_retirarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_relatorioActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            fecharSys();
    }//GEN-LAST:event_jb_editarKeyPressed

    private void jb_reporKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_reporKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_reporActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_retirarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_relatorioActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            fecharSys();
    }//GEN-LAST:event_jb_reporKeyPressed

    private void jb_deletarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_deletarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_reporActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_retirarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_relatorioActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            fecharSys();
    }//GEN-LAST:event_jb_deletarKeyPressed

    private void jb_retirarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_retirarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_reporActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_retirarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_relatorioActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            fecharSys();
    }//GEN-LAST:event_jb_retirarKeyPressed

    private void jb_relatorioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_relatorioKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_reporActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_retirarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_relatorioActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            fecharSys();
    }//GEN-LAST:event_jb_relatorioKeyPressed

    private void tf_pesqKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pesqKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_reporActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_retirarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_relatorioActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            fecharSys();
    }//GEN-LAST:event_tf_pesqKeyPressed

    private void rb_todosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_todosKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_reporActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_retirarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_relatorioActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            fecharSys();
    }//GEN-LAST:event_rb_todosKeyPressed

    private void rb_congeladosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_congeladosKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_reporActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_retirarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_relatorioActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            fecharSys();
    }//GEN-LAST:event_rb_congeladosKeyPressed

    private void rb_carnesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_carnesKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_reporActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_retirarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_relatorioActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            fecharSys();
    }//GEN-LAST:event_rb_carnesKeyPressed

    private void rb_avesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_avesKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_reporActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_retirarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_relatorioActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            fecharSys();
    }//GEN-LAST:event_rb_avesKeyPressed

    private void rb_peixesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_peixesKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_reporActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_retirarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_relatorioActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            fecharSys();
    }//GEN-LAST:event_rb_peixesKeyPressed

    private void rb_hortKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_hortKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_reporActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_retirarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_relatorioActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            fecharSys();
    }//GEN-LAST:event_rb_hortKeyPressed

    private void rb_sushiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_sushiKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_reporActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_retirarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_relatorioActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            fecharSys();
    }//GEN-LAST:event_rb_sushiKeyPressed

    private void rb_merceariaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_merceariaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_reporActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_retirarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_relatorioActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            fecharSys();
    }//GEN-LAST:event_rb_merceariaKeyPressed

    private void rb_padariaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_padariaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_reporActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_retirarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_relatorioActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            fecharSys();
    }//GEN-LAST:event_rb_padariaKeyPressed

    private void rb_friosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_friosKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_reporActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_retirarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_relatorioActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            fecharSys();
    }//GEN-LAST:event_rb_friosKeyPressed

    private void rb_limpezaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_limpezaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_reporActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_retirarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_relatorioActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            fecharSys();
    }//GEN-LAST:event_rb_limpezaKeyPressed

    private void tb_prodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_prodKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_F1)  
            jb_novoActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F2)  
            jb_editarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F3)  
            jb_reporActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_F4)  
            jb_deletarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F5)  
            jb_retirarActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_F6)  
            jb_relatorioActionPerformed(null);
        else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            fecharSys();
    }//GEN-LAST:event_tb_prodKeyPressed

    private void mi_novoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_novoUserActionPerformed
        // TODO add your handling code here:
        new NovoUserForm().show();
    }//GEN-LAST:event_mi_novoUserActionPerformed

    private void mi_editUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_editUserActionPerformed
        // TODO add your handling code here:
        new AlterarUserForm(user, senha).show();
    }//GEN-LAST:event_mi_editUserActionPerformed

    private void mi_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_sairActionPerformed
        // TODO add your handling code here:
        fecharSys();
    }//GEN-LAST:event_mi_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public void preencherTabela() throws SQLException, ParseException{
            
            ProdutoDAO dao = new ProdutoDAO();
            minhaList = dao.List(filtro);
            MyTableModel mtb = new MyTableModel(Produto.class, minhaList, tb_prod);
            tb_prod.setModel(mtb);
            tb_prod.getColumnModel().getColumn(0).setPreferredWidth(300);
            tb_prod.getColumnModel().getColumn(1).setPreferredWidth(100);
            tb_prod.getColumnModel().getColumn(2).setPreferredWidth(100);
            tb_prod.getColumnModel().getColumn(3).setPreferredWidth(300);
    }
    public void preecherTabelaPesq(List<Produto> minhaList){
        MyTableModel mtb = new MyTableModel(Produto.class, minhaList, tb_prod);
            tb_prod.setModel(mtb);
            tb_prod.getColumnModel().getColumn(0).setPreferredWidth(300);
            tb_prod.getColumnModel().getColumn(1).setPreferredWidth(100);
            tb_prod.getColumnModel().getColumn(2).setPreferredWidth(100);
            tb_prod.getColumnModel().getColumn(3).setPreferredWidth(300);
    }
    
    public void fecharSys(){
        if (JOptionPane.showConfirmDialog(null, "Deseja mesmo sair?", "Confirmação de saída", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            new LoginForm().show();
            dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_deletar;
    private javax.swing.JButton jb_editar;
    private javax.swing.JButton jb_novo;
    private javax.swing.JButton jb_relatorio;
    private javax.swing.JButton jb_repor;
    private javax.swing.JButton jb_retirar;
    private javax.swing.JMenuItem mi_editUser;
    private javax.swing.JMenuItem mi_novoUser;
    private javax.swing.JMenuItem mi_sair;
    private javax.swing.JRadioButton rb_aves;
    private javax.swing.JRadioButton rb_carnes;
    private javax.swing.JRadioButton rb_congelados;
    private javax.swing.JRadioButton rb_frios;
    private javax.swing.JRadioButton rb_hort;
    private javax.swing.JRadioButton rb_limpeza;
    private javax.swing.JRadioButton rb_mercearia;
    private javax.swing.JRadioButton rb_padaria;
    private javax.swing.JRadioButton rb_peixes;
    private javax.swing.JRadioButton rb_sushi;
    private javax.swing.JRadioButton rb_todos;
    private javax.swing.JTable tb_prod;
    private javax.swing.JTextField tf_pesq;
    // End of variables declaration//GEN-END:variables
}
